---
title: "confounding"
author: "Charlotte Fowler"
date: "12/5/2019"
output: html_document
---

```{r}
library(tidyverse)
```




```{r}
lawsuit = read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery"), 
    
         )
```


```{r}
base_mod = lm(ln_sal_avg ~ gender, data = lawsuit)
dept_mod = lm(ln_sal_avg ~ gender + dept, data = lawsuit)
clin_mod = lm(ln_sal_avg ~ gender + clin, data = lawsuit)
cert_mod = lm(ln_sal_avg ~ gender + cert, data = lawsuit)
prate_mod = lm(ln_sal_avg ~ gender + prate, data = lawsuit)
exper_mod = lm(ln_sal_avg ~ gender + exper, data = lawsuit)
rank_mod = lm(ln_sal_avg ~ gender + rank, data = lawsuit)
inter_dept_mod = lm(ln_sal_avg ~ gender * dept, data = lawsuit)
inter_clin_mod = lm(ln_sal_avg ~ gender * clin, data = lawsuit)
inter_cert_mod = lm(ln_sal_avg ~ gender * cert, data = lawsuit)
inter_prate_mod = lm(ln_sal_avg ~ gender * prate, data = lawsuit)
inter_exper_mod = lm(ln_sal_avg ~ gender * exper, data = lawsuit)
inter_rank_mod = lm(ln_sal_avg ~ gender * rank, data = lawsuit)
```


```{r}
summary(base_mod)
summary(dept_mod)
summary(clin_mod)
summary(cert_mod)
summary(prate_mod)
summary(exper_mod)
summary(rank_mod)
```
All vars besides rank are confounders in that they exagerate relationship of interest when not being controlled for.  

(check 10%)

```{r}
summary(inter_dept_mod)
summary(inter_clin_mod)
summary(inter_cert_mod)
summary(inter_prate_mod)
summary(inter_exper_mod)
summary(inter_rank_mod)
```
Only rank has significant interaction, which implies that rank is a possible effect modifier.

```{r}
lawsuit %>% 
  ggplot(aes(y = sal_avg, x = gender, fill = rank)) + 
  geom_bar(stat = "identity", position = "dodge")
```
For males being a full professor has a stronger effect than for females


```{r}
library(caret)
train_ctrl_cv10 <- trainControl(method = "cv", number = 10)


set.seed(1)
back_step <- train(
    ln_sal_avg ~ gender * rank + dept + clin + cert + prate + exper,
    data = lawsuit,
    method = "leapBackward",
    tuneGrid = data.frame(nvmax = 1:15),
    trControl = train_ctrl_cv10,
    na.action = na.omit,
    metric = "Rsquared"
)

coefficients(back_step$finalModel, id = back_step$bestTune$nvmax)
```

```{r}
coefficients(back_step$finalModel, id = back_step$bestTune$nvmax)
```


```{r}
lawsuit %>% 
  ggplot(aes(x = sal_avg, fill = gender)) + 
  geom_density(alpha = 0.5) + 
  xlim(36594.5, 445859)
```




```{r}
min(lawsuit$sal_avg)
mean(lawsuit$sal_avg)
```



```{r}
lawsuit_full_prof =  read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery") ) %>% 
  filter(rank == "full professor") %>% 
  select(-c(sal94, sal95, rank, id, sal_avg))
  



lawsuit_associate =  read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery") ) %>% 
  filter(rank == "associate") %>% 
  select(-c(sal94, sal95, rank, id, sal_avg))


lawsuit_assistant =  read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery") ) %>% 
  filter(rank == "assistant") %>% 
  select(-c(sal94, sal95, rank, id, sal_avg))
```

```{r}
full_prof_mod = lm(ln_sal_avg ~ . - prate , lawsuit_full_prof)

summary(full_prof_mod)
```


```{r}
assistant_mod = lm(ln_sal_avg ~ . - prate , lawsuit_assistant)

summary(assistant_mod)
```


```{r}
associate_mod = lm(ln_sal_avg ~ . - prate , lawsuit_associate)

summary(associate_mod)
```