---
title: "EDA"
author: "Rebecca Silva"
date: "12/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(arsenal)
```

```{r}
lawsuit = read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sal_avg = (sal94 + sal95)/2)
```

```{r, message = FALSE, echo = FALSE, warning=FALSE}

# change variable names/labels
my_labels <- list(dept = "Dept (n%)", gender = "Gender, Male (n%)", clin = "Clin, Clinical Emphasis (n%)", cert = "Certfified, Yes (n%)", prate = "Publication rate", exper = "Experience (years)", rank = "Rank (n%)", sal94 = "Salary 1994", sal95 = "Salary 1995", sal_avg = "Avg Salary") 

# clean the output
my_controls <- tableby.control(
               total = F,
               test=F,  
               digits = 2, 
               digits.pct = 2,
               cat.simplify = T, 
               numeric.stats = c("meansd", "medianq1q3"),
               cat.stats = c("countpct"),
               stats.labels = list(
               meansd = "Mean (±SD)",
               medianq1q3 = "Median (Q1, Q3)",
               countpct = "N (%)"))

# make categories factor vars to show N (%)
data_tabl<- lawsuit %>% 
          mutate(gender = factor(gender, labels= c("Female", "Male")), 
                 dept = factor(dept, labels = c("Bio/Molecular Biology", "Physiology", "Genetics", "Pediatrics", "Medicine", "Surgery")), 
                 clin = factor(clin, labels= c("Research emphasis", "Clinical emphasis")),
                 cert = factor(cert, labels= c("Not certified", "Board certified")),
                 rank = factor(rank, labels= c("Assistant", "Associate", "Full professor")))

```


```{r, results="asis", echo = FALSE}
# tabulation by group
tab1 <- tableby(gender ~dept + clin + cert + prate + exper + rank + sal94 + sal95 + sal_avg, 
                data=data_tabl, 
                control = my_controls)
summary(tab1, title = "Descriptive Statistics", 
        labelTranslations = my_labels, text=T) 
```

```{r}
lawsuit = read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery"), 
    
         )
```



```{r}
spineplot(factor(lawsuit$gender)~factor(lawsuit$rank), col = c("light blue", "light green", "blue"), 
          xlab = "Gender", ylab = "Rank")
```
```{r}
d <- lawsuit %>%
    count(gender, rank) %>%
    mutate(total = sum(n), 
           fraction = n / total)

lab <- d %>%
    #distinct(gender) %>%
    select(gender, total) %>%
    ungroup() %>%
    mutate(position = .5 * (cumsum(total) + cumsum(lag(total, default = 0))))

d %>%
    inner_join(lab) %>%
    ggplot(aes(position, fraction, fill = rank, width = total)) +
    geom_bar(stat = "identity") +
    scale_x_continuous(labels = lab$gender, breaks = lab$position) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    xlab("Manufacturer")
```


```{r}
lawsuit %>% 
  group_by(gender) %>% 
  count(rank) %>% 
  #group_by( gender)
  mutate(prop = n/ sum(n)) %>% 
  ggplot(aes(x = gender, y = prop, fill = rank)) + 
  geom_bar(stat = "identity") + 
  labs(x = "", y = "proportion")
```

