---
title: "EDA"
author: "Rebecca Silva"
date: "12/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(arsenal)
```

```{r}
lawsuit = read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sal_avg = (sal94 + sal95)/2)
```

```{r, message = FALSE, echo = FALSE, warning=FALSE}

# change variable names/labels
my_labels <- list(dept = "Dept (n%)", gender = "Gender, Male (n%)", clin = "Clin, Clinical Emphasis (n%)", cert = "Certfified, Yes (n%)", prate = "Publication rate", expersal94 = "Salary 1994", sal95 = "Salary 1995", sal_avg = "Avg Salary") 

# clean the output
my_controls <- tableby.control(
               total = F,
               test=F,  
               digits = 2, 
               digits.pct = 2,
               cat.simplify = T, 
               numeric.stats = c("meansd", "medianq1q3"),
               cat.stats = c("countpct"),
               stats.labels = list(
               meansd = "Mean (±SD)",
               medianq1q3 = "Median (Q1, Q3)",
               countpct = "N (%)"))

# make categories factor vars to show N (%)
data_tabl<- data %>% 
          mutate(gender = factor(gender, labels= c("Female", "Male"))) 

```


```{r, results="asis", echo = FALSE}
# tabulation by group
tab1 <- tableby(~totalcost + e_rvisits + age + gender + complications + duration, 
                data=data_tabl, 
                control = my_controls)
summary(tab1, title = "Descriptive Statistics", 
        labelTranslations = my_labels, text=T) 
```
