---
title: "final_project_code"
author: "Charlotte Fowler"
date: "12/8/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE)

theme_set(theme_minimal())

#loading packages
library(arsenal)
library(tidyverse)
library(corrplot)
library(GGally)
```



```{r}
#reading in data
lawsuit = read_csv("./Lawsuit.csv") %>% 
  mutate(sal_avg = (sal94 + sal95)/2)
```

```{r, results="asis"}
#descriptive table
my_labels <- list(dept = "Dept (n%)", gender = "Gender, Male (n%)", clin = "Clin, Clinical Emphasis (n%)", cert = "Certfified, Yes (n%)", prate = "Publication rate", exper = "Experience (years)", rank = "Rank (n%)", sal94 = "Salary 1994", sal95 = "Salary 1995", sal_avg = "Avg Salary") 


my_controls <- tableby.control(
               total = F,
               test=F,  
               digits = 2, 
               digits.pct = 2,
               cat.simplify = T, 
               numeric.stats = c("meansd", "medianq1q3"),
               cat.stats = c("countpct"),
               stats.labels = list(
               meansd = "Mean (±SD)",
               medianq1q3 = "Median (Q1, Q3)",
               countpct = "N (%)"))


data_tabl<- lawsuit %>% 
          mutate(gender = factor(gender, labels= c("Female", "Male")), 
                 dept = factor(dept, labels = c("Bio/Molecular Biology", "Physiology", "Genetics", "Pediatrics", "Medicine", "Surgery")), 
                 clin = factor(clin, labels= c("Research emphasis", "Clinical emphasis")),
                 cert = factor(cert, labels= c("Not certified", "Board certified")),
                 rank = factor(rank, labels= c("Assistant", "Associate", "Full professor")))

tab1 <- tableby(gender ~dept + clin + cert + prate + exper + rank + sal94 + sal95 + sal_avg, 
                data=data_tabl, 
                control = my_controls)
summary(tab1, title = "Descriptive Statistics", 
        labelTranslations = my_labels, text=T) 
```


```{r}
#cleaning data
lawsuit = read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery"), 
    
         )
```

```{r}
#######descriptive plots########## 
#salary and gender
lawsuit %>% 
  mutate(gender = recode(gender, "0" = "female", "1" = "male")) %>% 
  ggplot(aes(y = sal_avg, x = gender)) + 
  geom_boxplot() + 
  labs(title = "Salary by Gender" , y = "salary", x = "")

#salary and experience
lawsuit %>% 
  ggplot(aes(y = sal_avg, x = exper)) + 
  geom_point() + 
  labs(title = "Salary by Experience", y = "salary", x = "experience (yrs)")

#correlation plot 


lawsuit_cor = lawsuit %>% 
  select(-id, - sal94, -sal95)
cor(lawsuit_cor) %>%                            
  corrplot(method = "circle", type = "upper", diag=FALSE, title = "")
```



```{r}
#histograms of response var
library(patchwork)
reg_dense = lawsuit %>% 
  ggplot(aes(x = sal_avg)) + 
  geom_histogram(alpha = .6, color = "black") + 
  labs(x = "salary", y = "count", title = "Salary Histogram")

ln_dens = lawsuit %>% 
  ggplot(aes(x = ln_sal_avg)) + 
  geom_histogram(alpha = .6, color = "black") + 
  labs(x = "ln(salary)", y = "", title = "Transformed Histogram")

reg_dense + ln_dens
```

```{r}
#####looking for confounding #######

#building models
base_mod = lm(ln_sal_avg ~ gender, data = lawsuit)
dept_mod = lm(ln_sal_avg ~ gender + dept, data = lawsuit)
clin_mod = lm(ln_sal_avg ~ gender + clin, data = lawsuit)
cert_mod = lm(ln_sal_avg ~ gender + cert, data = lawsuit)
prate_mod = lm(ln_sal_avg ~ gender + prate, data = lawsuit)
exper_mod = lm(ln_sal_avg ~ gender + exper, data = lawsuit)
rank_mod = lm(ln_sal_avg ~ gender + rank, data = lawsuit)

#checking coefficients and p-values
summary(base_mod)
summary(dept_mod)
summary(clin_mod)
summary(cert_mod)
summary(prate_mod)
summary(rank_mod)

#calculating percent difference 
#dept
(.3853- 0.2052)/.3853
#clin
(.3853- 0.3372)/.3853
#cert
(.3853- .3328)/.3853
#prate
(.3853- 0.3372)/.3853
#exper
(.3853- 0.30755)/.3853
#rank
(.3853- 0.349481)/.3853
```

```{r}
#looking for modifiers 
inter_dept_mod = lm(ln_sal_avg ~ gender * dept, data = lawsuit)
inter_clin_mod = lm(ln_sal_avg ~ gender * clin, data = lawsuit)
inter_cert_mod = lm(ln_sal_avg ~ gender * cert, data = lawsuit)
inter_prate_mod = lm(ln_sal_avg ~ gender * prate, data = lawsuit)
inter_exper_mod = lm(ln_sal_avg ~ gender * exper, data = lawsuit)
inter_rank_mod = lm(ln_sal_avg ~ gender * rank, data = lawsuit)

summary(inter_dept_mod)
summary(inter_clin_mod)
summary(inter_cert_mod)
summary(inter_prate_mod)
summary(inter_exper_mod)
summary(inter_rank_mod)
```

```{r}
#data for model 
lawsuit_model = read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    sal_avg = (sal94 + sal95)/2, 
    ln_sal_avg = log(sal_avg), 
    gender = recode(gender, "0" = "female", "1" = "male"),
    clin = recode(clin, "0" = "research", "1" = "clinical"), 
    cert = recode(cert, "0" = "not certified", "1" = "certified"), 
    rank = recode(rank, "1" = "assistant", "2" = "associate", "3" = "full professor"),
    dept = recode(dept, "1" = "biochemistry", "2" = "physiology", "3" = "genetics", "4" = "pediatrics", "5" = "medicine", "6" = "surgery") ) %>% 
  select(-c(sal94, sal95, sal_avg))

#full model 
full_model = lm(ln_sal_avg ~ gender * rank + . - id, lawsuit_model)
summary(full_model)
```

```{r}
#vif calc 
vif(full_model)

#no prate model 
full_model_no_prate = lm(ln_sal_avg ~ gender * rank + . - prate- id, lawsuit_model)
summary(full_model_no_prate)

vif(full_model_no_prate)
```



